name: Elixir Test CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.10-slim

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run tests
      run: MIX_ENV=test mix test
    - name: Run credo
      run: mix credo
